### ISSUE TITLE
"lein deploy-storm --start --name mycluster" does not work

### ISSUE THREAD

**Issue by vipulneo** [nathanmarz/storm-deploy#49]
Hi,
I tried installing Storm on ec2 with "lein deploy-storm --start --name mycluster --branch 0.8.3" Whilt installing it show everything OK but when I tailed nohup.out. It continuously throws this error.
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/command/config_value
Caused by: java.lang.ClassNotFoundException: backtype.storm.command.config_value
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: backtype.storm.command.config_value. Program will exit.
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/command/config_value
Caused by: java.lang.ClassNotFoundException: backtype.storm.command.config_value
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: backtype.storm.command.config_value. Program will exit.
Running: java -server -Dstorm.options= -Dstorm.home=/home/storm/storm-0.8.2 -Djava.library.path= -Dstorm.conf.file= -cp /home/storm/storm-0.8.2/log4j:/home/storm/storm-0.8.2/conf -Dlogfile.name=nimbus.log -Dlog4j.configuration=storm.log.properties backtype.storm.daemon.nimbus
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/daemon/nimbus
Caused by: java.lang.ClassNotFoundException: backtype.storm.daemon.nimbus
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: backtype.storm.daemon.nimbus. Program will exit

And When I tried this "lein deploy-storm --start --name my cluster" there is some maven build error.

Thanks,
Vipul

**Comment by vipulneo** [comment]
Finally it worked with 0.9.0-rc2

**Comment by lorcan** [comment]
Hi Vipul,
Is there any chance you could send me the full log output of these
failures. I would have expected "lein deploy-storm --start --name mycluster
--branch 0.8.3" to work properly (if run with the changes from pull-request
#48)?
Glad you got it working with 0.9.0-rc2 in any case.
Best,
Lorcan

**Comment by vipulneo** [comment]
As I mentioned above It doesn't throw any error while installation, But when I ssh on Nimbus I didn't saw any jars in the lib folder. When I tailed nohup.out nothing was apart of the error I have mentioned above and it was getting logged continuously.

**Comment by lorcan** [comment]
ok, thanks Vipul, I'll assume this wasn't a storm-deploy problem then.
